@url = http://localhost:3000

### Make a GET request to the URL
GET {{url}}

### Name parameter
GET {{url}}/hello/Dieter

### Query parameter
GET {{url}}/hello/Dieter/20

### Query parameter
GET {{url}}/hello2/Dieter/20?includeAddress=true


### Post Person
POST {{url}}/person
Content-Type: application/json

{
    "firstName": "Dieter",
    "lastName": "Hubau"
}

### Get settings
GET {{url}}/settings


### Get settings
GET {{url}}/settings2